# AUTO-GENERATED BY GUI
import os
import numpy as np

# --- Paths ---
SESSION_CONFIGS = [
    {"type": "manual", "data_file": r"E:/eTheremin/SKIEUR/SKIEUR_20260316_SESSION_00/headstage_0/data_0.005.npy", "dt": 0.005},
    {"type": "manual", "data_file": r"E:/eTheremin/SKIEUR/SKIEUR_20260316_SESSION_00/headstage_0/features_0.02.npy", "dt": 0.005}
]

UNIQUE_TONES_PATH = r"C:\Users\PenPen\Desktop\Ferret\Data\Bohan\unique_tones\unique_tones.npy"
OUTPUT_DIR = r"C:\Users\PenPen\Desktop\Ferret\Code\Results"
CACHE_PATH = r"C:\Users\PenPen\Desktop\Ferret\Code\cache\preprocessed_data.pkl"

# --- Signal Parameters ---
DT = 0.005
T_PRE = 0.3
T_POST = 0.3

N_BINS_PRE = int(T_PRE / DT)
N_BINS_POST = int(T_POST / DT)
EXPECTED_LENGTH = N_BINS_PRE + N_BINS_POST

BASELINE_BINS = int(0.2 / DT)
IDX_BASE_START = N_BINS_PRE - BASELINE_BINS
IDX_BASE_END = N_BINS_PRE
IDX_PEAK_START = N_BINS_PRE
IDX_PEAK_END = EXPECTED_LENGTH

# --- Analysis Parameters ---
N_VALUES = [1, 2, 4, 8, 16, 32, 64, 128, 256]
N_PER_GROUP = 5
N_GROUPS = 3

# --- NEW: Checkbox Value ---
RUN_CHUNK_FDR = True
